services:
  caddy:
    image: caddy:2-alpine
    container_name: proxy_caddy
    restart: unless-stopped
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}   # ← AJOUT
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

networks:
  web:
    external: true
    name: web

volumes:
  caddy_data:
  caddy_config:
